# Generated by Django 3.2 on 2021-04-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadvideo',
            name='url',
        ),
        migrations.AddField(
            model_name='downloadvideo',
            name='multiUrls',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='downloadvideo',
            name='singleUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
