# Generated by Django 3.2 on 2021-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20210427_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadvideo',
            old_name='singleUrl',
            new_name='download_directory',
        ),
        migrations.RemoveField(
            model_name='downloadvideo',
            name='multiUrls',
        ),
        migrations.AddField(
            model_name='downloadvideo',
            name='file_upload',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='downloadvideo',
            name='url_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloadvideo',
            name='video_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
