# Generated by Django 3.2 on 2021-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_auto_20210517_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadvideo',
            name='download_directory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadvideo',
            name='file_upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='downloadvideo',
            name='url_area',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='downloadvideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
